name = "vmddp_web"
compatibility_date = "2025-10-09"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_FRAPPE_BASE_URL = "https://portal.vmddp.com"
NEXT_PUBLIC_BASE_URL = "https://vmddp.com"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NEXT_PUBLIC_FRAPPE_BASE_URL = "https://portal.vmddp.com"
NEXT_PUBLIC_BASE_URL = "https://vmddp.com"

[env.preview]
compatibility_flags = ["nodejs_compat"]

[env.preview.vars]
NEXT_PUBLIC_FRAPPE_BASE_URL = "https://gov-vmddp.klaimify.in"
NEXT_PUBLIC_BASE_URL = "https://main.vmddp-web.pages.dev"

[env.production.vars]
NEXT_GOOGLE_TAG_MANAGER="GTM-5KQ84FVB"

